### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by akdetrick** [sjhcockrell/antimony#20]
"ERROR: Resource download failed for "
```
R_tputcolors="https://github.com/sjhcockrell/tputcolors/archive/1.0.tar.gz"        # bash coloring
R_apacheBatik="https://github.com/sjhcockrell/Apache-Batik-1.7/archive/1.7.tar.gz" # .ttf => .svg
```

**Comment by kristencs** [comment]
I CAN CONFIRM THAT THIS IS BAD AND SHOULD BE FIXED

![screen shot 2015-04-17 at 5 02 19 pm](https://cloud.githubusercontent.com/assets/10536480/7210892/a442a7dc-e523-11e4-9092-350e270ecf95.png)

**Comment by sjhcockrell** [comment]
Don't use wget; use curl instead
