### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by kristencs** [sjhcockrell/antimony#23]
Checking for dependency fontforge...
Installing dependency fontforge...
(This will take a couple minutes. Go get some coffee.)
./install: line 209: error: command not found
DEBUG TRACE:
cairo: XQuartz is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz

You can download from:
  https://xquartz.macosforge.org
pango: XQuartz is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz

You can download from:
  https://xquartz.macosforge.org
Error: Unsatisified requirements failed this build.

**Comment by sjhcockrell** [comment]
I think this _should_ be fixed.
